export interface ClipboardItem {
  id: string
  content: string
  originalContent?: string
  type: 'text' | 'image'
  timestamp: number
  isPinned: boolean
  isCleaned: boolean
  charsRemoved: number
  appSource?: string
  pinOrder?: number
}

export interface CleaningResult {
  cleanedText: string
  originalText: string
  charsRemoved: number
  removedChars: RemovedCharDetail[]
}

export interface RemovedCharDetail {
  char: string
  name: string
  count: number
  codePoint: string
}

export interface AppSettings {
  // General
  hotkey: string
  clipboardCheckInterval: number
  maxHistorySize: number
  pasteAutomatically: boolean
  launchAtLogin: boolean
  soundEffects: boolean

  // Appearance
  popupPosition: 'tray' | 'center' | 'cursor'
  showFooter: boolean
  showItemCount: boolean
  theme: 'system' | 'dark' | 'light'

  // AutomaticClean
  cleanOnCopy: boolean
  showCleaningBadge: boolean
  removeZeroWidth: boolean
  removeSoftHyphens: boolean
  removeDirectionalMarks: boolean
  removeInvisibleMath: boolean
  normalizeNonBreakingSpaces: boolean
  normalizeSmartQuotes: boolean
  preserveEmojiZWJ: boolean

  // Ignore
  ignoredApps: string[]
  ignoredPasteTypes: string[]
}

export const DEFAULT_SETTINGS: AppSettings = {
  hotkey: 'Shift+CommandOrControl+V',
  clipboardCheckInterval: 500,
  maxHistorySize: 200,
  pasteAutomatically: true,
  launchAtLogin: false,
  soundEffects: false,

  popupPosition: 'tray',
  showFooter: true,
  showItemCount: false,
  theme: 'system',

  cleanOnCopy: true,
  showCleaningBadge: true,
  removeZeroWidth: true,
  removeSoftHyphens: true,
  removeDirectionalMarks: true,
  removeInvisibleMath: true,
  normalizeNonBreakingSpaces: true,
  normalizeSmartQuotes: false,
  preserveEmojiZWJ: true,

  ignoredApps: [],
  ignoredPasteTypes: [
    'org.nspasteboard.TransientType',
    'org.nspasteboard.ConcealedType',
    'org.nspasteboard.AutoGeneratedType',
    'com.agilebits.onepassword'
  ]
}

export type IpcChannel =
  | 'clipboard:get-history'
  | 'clipboard:search'
  | 'clipboard:delete-item'
  | 'clipboard:pin-item'
  | 'clipboard:paste-item'
  | 'clipboard:copy-item'
  | 'clipboard:clear-history'
  | 'clipboard:clean-text'
  | 'settings:get'
  | 'settings:update'
  | 'window:close-popup'
  | 'window:open-settings'
  | 'app:get-stats'
  | 'app:get-version'
